<?php
if ( ! defined( 'ABSPATH' ) ) exit;

class Etch_Transfer_Importer {

    /**
     * Main entry point. Accepts both single and multi-export bundles.
     * Always auto-matches by post_type + slug.
     */
    public static function import( $json ) {
        if ( empty( $json ) ) {
            return new WP_Error( 'no_data', 'No JSON data provided.' );
        }

        $data = json_decode( $json, true );

        if ( isset( $data['success'] ) && isset( $data['data'] ) ) {
            $data = $data['data'];
        }

        if ( ! $data || ! isset( $data['etch_export_version'] ) ) {
            return new WP_Error( 'invalid_json', 'Invalid export file. Please use a file generated by Etch Transfer.' );
        }

        // Normalise single export into multi-item shape for unified processing
        if ( ! isset( $data['etch_export_type'] ) || $data['etch_export_type'] !== 'multi' ) {
            $data = [
                'etch_export_version' => $data['etch_export_version'],
                'etch_export_type'    => 'multi',
                'source_site'         => $data['source_site'] ?? '',
                'item_count'          => 1,
                'items'               => [ $data ],
                'etch_styles'         => $data['etch_styles'] ?? [],
            ];
        }

        return self::process_bundle( $data );
    }

    private static function process_bundle( $data ) {
        $imported = [];
        $created  = [];
        $errors   = [];

        foreach ( $data['items'] as $item ) {
            $dest_post = self::resolve_destination( $item );

            if ( is_wp_error( $dest_post ) ) {
                $errors[] = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $dest_post->get_error_message();
                continue;
            }

            $is_new = isset( $dest_post->_is_new ) && $dest_post->_is_new;
            $result = self::write_post( $item, $dest_post->ID );

            if ( is_wp_error( $result ) ) {
                $errors[] = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $result->get_error_message();
                continue;
            }

            if ( $is_new ) {
                $created[] = $item['post_title'] ?? '(untitled)';
            } else {
                $imported[] = $item['post_title'] ?? '(untitled)';
            }
        }

        $styles = self::merge_styles( $data['etch_styles'] ?? [] );

        wp_cache_flush();

        $parts = [];
        if ( ! empty( $imported ) ) $parts[] = count( $imported ) . ' updated';
        if ( ! empty( $created  ) ) $parts[] = count( $created  ) . ' created';
        if ( ! empty( $errors   ) ) $parts[] = count( $errors   ) . ' failed';

        $msg = 'Import complete from ' . ( $data['source_site'] ?? 'unknown' ) . '. '
             . implode( ', ', $parts ) . '. '
             . $styles['merged'] . ' Etch styles merged.';

        if ( ! empty( $errors ) ) {
            $msg .= ' Errors: ' . implode( '; ', $errors );
        }

        return [
            'message'       => $msg,
            'imported'      => $imported,
            'created'       => $created,
            'errors'        => $errors,
            'styles_merged' => $styles['merged'],
        ];
    }

    /**
     * Find existing post by post_type + slug, or create a new one.
     */
    private static function resolve_destination( $item ) {
        $post_type = $item['source_post_type'] ?? 'page';
        $slug      = $item['source_post_name']  ?? '';
        $title     = $item['post_title']         ?? '';

        if ( $slug ) {
            $existing = get_posts([
                'post_type'      => $post_type,
                'name'           => $slug,
                'post_status'    => 'any',
                'posts_per_page' => 1,
            ]);

            // Fallback for wp_template slugs that include theme prefix (theme//slug)
            if ( empty( $existing ) && $post_type === 'wp_template' && str_contains( $slug, '//' ) ) {
                $short_slug = substr( $slug, strpos( $slug, '//' ) + 2 );
                $existing   = get_posts([
                    'post_type'      => $post_type,
                    'name'           => $short_slug,
                    'post_status'    => 'any',
                    'posts_per_page' => 1,
                ]);
            }

            if ( ! empty( $existing ) ) {
                return $existing[0];
            }
        }

        // Create new
        $new_id = wp_insert_post([
            'post_title'   => $title,
            'post_name'    => $slug,
            'post_type'    => $post_type,
            'post_status'  => $item['post_status'] ?? 'publish',
            'post_content' => '',
        ], true );

        if ( is_wp_error( $new_id ) ) {
            return new WP_Error( 'create_failed', 'Could not create: ' . $new_id->get_error_message() );
        }

        $post          = get_post( $new_id );
        $post->_is_new = true;
        return $post;
    }

    /**
     * Write post content + meta directly via $wpdb, bypassing kses which
     * corrupts Etch's \u0022 / \u0026 sequences in block comment JSON.
     */
    private static function write_post( $item, $dest_post_id ) {
        global $wpdb;

        $updated = $wpdb->update(
            $wpdb->posts,
            [
                'post_content' => $item['post_content'],
                'post_status'  => $item['post_status'],
                'post_title'   => $item['post_title'],
            ],
            [ 'ID' => $dest_post_id ]
        );

        if ( $updated === false ) {
            return new WP_Error( 'db_error', 'DB write failed: ' . $wpdb->last_error );
        }

        // Replace meta
        $wpdb->delete( $wpdb->postmeta, [ 'post_id' => $dest_post_id ], [ '%d' ] );

        foreach ( ( $item['meta'] ?? [] ) as $row ) {
            $wpdb->insert(
                $wpdb->postmeta,
                [
                    'post_id'    => $dest_post_id,
                    'meta_key'   => $row['meta_key'],
                    'meta_value' => $row['meta_value'],
                ],
                [ '%d', '%s', '%s' ]
            );
        }

        clean_post_cache( $dest_post_id );
        return true;
    }

    private static function merge_styles( $incoming ) {
        if ( empty( $incoming ) || ! is_array( $incoming ) ) {
            return [ 'merged' => 0, 'skipped' => 0 ];
        }

        $dest = get_option( 'etch_styles', [] );
        if ( is_string( $dest ) ) $dest = maybe_unserialize( $dest );
        if ( ! is_array( $dest ) ) $dest = [];

        $merged = $skipped = 0;

        foreach ( $incoming as $id => $style ) {
            if ( isset( $dest[ $id ] ) ) { $skipped++; }
            else { $dest[ $id ] = $style; $merged++; }
        }

        update_option( 'etch_styles', $dest );
        return [ 'merged' => $merged, 'skipped' => $skipped ];
    }
}
