<?php
if ( ! defined( 'ABSPATH' ) ) exit;

class Etch_Transfer_Importer {

    public static function import( $json ) {
        if ( empty( $json ) ) {
            return new WP_Error( 'no_data', 'No JSON data provided.' );
        }

        $data = json_decode( $json, true );

        if ( isset( $data['success'] ) && isset( $data['data'] ) ) {
            $data = $data['data'];
        }

        if ( ! $data || ! isset( $data['etch_export_version'] ) ) {
            return new WP_Error( 'invalid_json', 'Invalid export file. Please use a file generated by Etch Transfer.' );
        }

        if ( ! isset( $data['etch_export_type'] ) || $data['etch_export_type'] !== 'multi' ) {
            $data = [
                'etch_export_version' => $data['etch_export_version'],
                'etch_export_type'    => 'multi',
                'source_site'         => $data['source_site'] ?? '',
                'source_theme'        => $data['source_theme'] ?? '',
                'item_count'          => 1,
                'items'               => [ $data ],
                'wsf_forms'           => [],
                'etch_styles'         => $data['etch_styles'] ?? [],
            ];
        }

        return self::process_bundle( $data );
    }

    private static function process_bundle( $data ) {
        $imported = [];
        $created  = [];
        $errors   = [];

        // ── WS Forms first — build old→new ID map before rewriting page content ──
        $wsf_id_map   = [];
        $wsf_imported = [];
        $wsf_created  = [];

        foreach ( ( $data['wsf_forms'] ?? [] ) as $wsf_entry ) {
            $result = self::import_wsform( $wsf_entry );

            if ( is_wp_error( $result ) ) {
                $errors[] = '"' . ( $wsf_entry['label'] ?? '?' ) . '": ' . $result->get_error_message();
                continue;
            }

            $old_id = intval( $wsf_entry['source_form_id'] ?? ( $wsf_entry['form_object']['id'] ?? 0 ) );
            if ( $old_id > 0 ) {
                $wsf_id_map[ $old_id ] = $result['id'];
            }

            if ( $result['is_new'] ) {
                $wsf_created[]  = $wsf_entry['label'] ?? '(untitled)';
            } else {
                $wsf_imported[] = $wsf_entry['label'] ?? '(untitled)';
            }
        }

        // ── Standard post items ──────────────────────────────────────────────
        // Two-pass approach:
        // Pass 1: import all wp_block (component) items first to build a
        //         source_id → dest_id map, then rewrite refs in templates/pages.
        // Pass 2: import everything else with refs already rewritten.

        $component_id_map = []; // [ source_post_id => dest_post_id ]
        $deferred_items   = []; // non-component items processed in pass 2

        foreach ( ( $data['items'] ?? [] ) as $item ) {
            if ( ( $item['source_post_type'] ?? '' ) === 'wp_block' ) {
                $dest_post = self::resolve_destination( $item );

                if ( is_wp_error( $dest_post ) ) {
                    $errors[] = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $dest_post->get_error_message();
                    continue;
                }

                $is_new = isset( $dest_post->_is_new ) && $dest_post->_is_new;
                $result = self::write_post( $item, $dest_post->ID );

                if ( is_wp_error( $result ) ) {
                    $errors[] = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $result->get_error_message();
                    continue;
                }

                // Map source ID → dest ID for ref rewriting
                $src_id = intval( $item['source_post_id'] ?? 0 );
                if ( $src_id > 0 ) {
                    $component_id_map[ $src_id ] = $dest_post->ID;
                }

                if ( $is_new ) {
                    $created[] = $item['post_title'] ?? '(untitled)';
                } else {
                    $imported[] = $item['post_title'] ?? '(untitled)';
                }
            } else {
                $deferred_items[] = $item;
            }
        }

        // Pass 2: process templates, pages, patterns etc. with rewritten refs
        foreach ( $deferred_items as $item ) {
            $dest_post = self::resolve_destination( $item );

            if ( is_wp_error( $dest_post ) ) {
                $errors[] = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $dest_post->get_error_message();
                continue;
            }

            // Rewrite etch/component ref IDs
            if ( ! empty( $component_id_map ) ) {
                $item['post_content']          = self::rewrite_component_refs( $item['post_content'], $component_id_map );
                $item['post_content_filtered'] = self::rewrite_component_refs( $item['post_content_filtered'] ?? '', $component_id_map );
            }

            // Rewrite WS Form IDs
            if ( ! empty( $wsf_id_map ) ) {
                $item['post_content'] = self::rewrite_wsf_ids( $item['post_content'], $wsf_id_map );
            }

            $is_new = isset( $dest_post->_is_new ) && $dest_post->_is_new;
            $result = self::write_post( $item, $dest_post->ID );

            if ( is_wp_error( $result ) ) {
                $errors[] = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $result->get_error_message();
                continue;
            }

            if ( $is_new ) {
                $created[] = $item['post_title'] ?? '(untitled)';
            } else {
                $imported[] = $item['post_title'] ?? '(untitled)';
            }
        }

        $styles      = self::merge_styles( $data['etch_styles'] ?? [] );
        $gss_result  = self::merge_global_stylesheets( $data['etch_global_stylesheets'] ?? [] );
        $loop_result = self::merge_loops( $data['etch_loops'] ?? [] );

        wp_cache_flush();

        $parts = [];
        if ( ! empty( $imported )     ) $parts[] = count( $imported )     . ' updated';
        if ( ! empty( $created )      ) $parts[] = count( $created )      . ' created';
        if ( ! empty( $wsf_imported ) ) $parts[] = count( $wsf_imported ) . ' WS Forms updated';
        if ( ! empty( $wsf_created )  ) $parts[] = count( $wsf_created )  . ' WS Forms created';
        if ( ! empty( $errors )       ) $parts[] = count( $errors )       . ' failed';

        $msg = 'Import complete from ' . ( $data['source_site'] ?? 'unknown' ) . '. '
             . implode( ', ', $parts ) . '. '
             . $styles['merged'] . ' Etch styles merged. '
             . $gss_result['merged'] . ' global stylesheets merged. '
             . $loop_result['merged'] . ' loops merged.';

        if ( ! empty( $errors ) ) {
            $msg .= ' Errors: ' . implode( '; ', $errors );
        }

        return [
            'message'       => $msg,
            'imported'      => array_merge( $imported, $wsf_imported ),
            'created'       => array_merge( $created,  $wsf_created ),
            'errors'        => $errors,
            'styles_merged' => $styles['merged'],
        ];
    }

    /**
     * Resolve the destination post for an imported item.
     *
     * For wp_template:
     *   Etch stores templates with a bare slug (e.g. "index", "404", "home")
     *   and associates them with a theme via the wp_theme taxonomy.
     *
     *   Strategy:
     *   1. Find all wp_template posts whose post_name matches the bare slug
     *      (either exact or with any theme// prefix — covers both Etch-style
     *      and standard WordPress FSE style slugs).
     *   2. Pick the one whose wp_theme term matches the DESTINATION active theme.
     *   3. If none match the dest theme, pick the lowest ID and reassociate it.
     *   4. Never create duplicates — always write into an existing record.
     *   5. Only create new if absolutely no match exists at all.
     */
    private static function resolve_destination( $item ) {
        global $wpdb;

        $post_type = $item['source_post_type'] ?? 'page';
        $slug      = $item['source_post_name']  ?? '';
        $title     = $item['post_title']         ?? '';

        if ( $post_type === 'wp_template' ) {
            // Bare slug = part after // if prefixed, otherwise the full slug
            $bare_slug = str_contains( $slug, '//' )
                ? substr( $slug, strpos( $slug, '//' ) + 2 )
                : $slug;

            $dest_theme = get_stylesheet();

            // Find ALL existing templates matching this bare slug
            // (exact match OR theme-prefixed match)
            $all_ids = $wpdb->get_col( $wpdb->prepare(
                "SELECT ID FROM {$wpdb->posts}
                 WHERE post_type = 'wp_template'
                   AND post_status != 'trash'
                   AND ( post_name = %s OR post_name LIKE %s )
                 ORDER BY ID ASC",
                $bare_slug,
                '%//' . $wpdb->esc_like( $bare_slug )
            ) );

            $all_ids = array_map( 'intval', $all_ids );

            if ( ! empty( $all_ids ) ) {
                // Prefer the one already associated with the destination theme
                $preferred_id = null;
                foreach ( $all_ids as $candidate_id ) {
                    $terms = wp_get_object_terms( $candidate_id, 'wp_theme', [ 'fields' => 'names' ] );
                    if ( ! is_wp_error( $terms ) && in_array( $dest_theme, $terms, true ) ) {
                        $preferred_id = $candidate_id;
                        break;
                    }
                }

                // Fall back to lowest ID if none match the dest theme
                $dest_id = $preferred_id ?? $all_ids[0];

                // Ensure this record is associated with the destination theme
                wp_set_object_terms( $dest_id, $dest_theme, 'wp_theme', false );

                return get_post( $dest_id );
            }

            // No existing template — create one and associate with dest theme
            $new_id = wp_insert_post( [
                'post_title'   => $title,
                'post_name'    => $bare_slug,
                'post_type'    => 'wp_template',
                'post_status'  => 'publish',
                'post_content' => '',
            ], true );

            if ( is_wp_error( $new_id ) ) {
                return new WP_Error( 'create_failed', 'Could not create template: ' . $new_id->get_error_message() );
            }

            wp_set_object_terms( $new_id, $dest_theme, 'wp_theme', false );

            $post          = get_post( $new_id );
            $post->_is_new = true;
            return $post;
        }

        // ── All other post types: match by exact slug ─────────────────────────
        if ( $slug ) {
            $existing = get_posts( [
                'post_type'      => $post_type,
                'name'           => $slug,
                'post_status'    => 'any',
                'posts_per_page' => 1,
            ] );

            if ( ! empty( $existing ) ) {
                return $existing[0];
            }
        }

        $new_id = wp_insert_post( [
            'post_title'   => $title,
            'post_name'    => $slug,
            'post_type'    => $post_type,
            'post_status'  => $item['post_status'] ?? 'publish',
            'post_content' => '',
        ], true );

        if ( is_wp_error( $new_id ) ) {
            return new WP_Error( 'create_failed', 'Could not create: ' . $new_id->get_error_message() );
        }

        $post          = get_post( $new_id );
        $post->_is_new = true;
        return $post;
    }

    /**
     * Write all post fields directly via $wpdb, bypassing kses.
     *
     * post_content_filtered carries Etch conditions/structure.
     * For wp_template: preserve the destination's existing post_name
     * (whether bare "index" or theme-prefixed "theme//index").
     */
    private static function write_post( $item, $dest_post_id ) {
        global $wpdb;

        $post_type = $item['source_post_type'] ?? 'post';

        $fields = [
            'post_title'            => $item['post_title']            ?? '',
            'post_status'           => 'publish',
            'post_content'          => $item['post_content']          ?? '',
            'post_content_filtered' => $item['post_content_filtered'] ?? '',
            'post_excerpt'          => $item['post_excerpt']          ?? '',
        ];

        // Keep destination's own post_name for templates.
        // For everything else write the source slug so page URLs stay correct.
        if ( $post_type !== 'wp_template' ) {
            $fields['post_name'] = $item['source_post_name'] ?? '';
        }

        $updated = $wpdb->update( $wpdb->posts, $fields, [ 'ID' => $dest_post_id ] );

        if ( $updated === false ) {
            return new WP_Error( 'db_error', 'DB write failed: ' . $wpdb->last_error );
        }

        // Replace all post meta
        $wpdb->delete( $wpdb->postmeta, [ 'post_id' => $dest_post_id ], [ '%d' ] );

        foreach ( ( $item['meta'] ?? [] ) as $row ) {
            $wpdb->insert(
                $wpdb->postmeta,
                [
                    'post_id'    => $dest_post_id,
                    'meta_key'   => $row['meta_key'],
                    'meta_value' => $row['meta_value'],
                ],
                [ '%d', '%s', '%s' ]
            );
        }

        clean_post_cache( $dest_post_id );
        return true;
    }

    /**
     * Rewrite etch/component ref IDs in post content.
     *
     * Block markup: <!-- wp:etch/component {"ref":123,"attributes":{}} -->
     * The "ref" value is the wp_block post ID on the source site.
     * We replace it with the corresponding ID on the destination site.
     */
    private static function rewrite_component_refs( $content, $id_map ) {
        if ( empty( $content ) || empty( $id_map ) ) {
            return $content;
        }

        // Match "ref": 123 inside etch/component block comments
        // The ref is always a bare integer (no quotes around it)
        return preg_replace_callback(
            '/(<!--\s*wp:etch\/component\s+\{[^}]*"ref"\s*:\s*)(\d+)/i',
            function ( $matches ) use ( $id_map ) {
                $old_id = intval( $matches[2] );
                $new_id = $id_map[ $old_id ] ?? $old_id;
                return $matches[1] . $new_id;
            },
            $content
        );
    }

    /**
     * Rewrite WS Form IDs in post content.
     */
    private static function rewrite_wsf_ids( $content, $id_map ) {
        if ( empty( $content ) || empty( $id_map ) ) {
            return $content;
        }

        $content = preg_replace_callback(
            '/(<!--\s*wp:wsf-block\/form-add\s+)(\{[^}]*"form_id"\s*:\s*")(\d+)(")/i',
            function ( $matches ) use ( $id_map ) {
                $old_id = intval( $matches[3] );
                $new_id = $id_map[ $old_id ] ?? $old_id;
                return $matches[1] . $matches[2] . $new_id . $matches[4];
            },
            $content
        );

        $content = preg_replace_callback(
            '/(\[ws_form\b[^\]]*\bid\s*=\s*["\'])(\d+)(["\'][^\]]*\])/i',
            function ( $matches ) use ( $id_map ) {
                $old_id = intval( $matches[2] );
                $new_id = $id_map[ $old_id ] ?? $old_id;
                return $matches[1] . $new_id . $matches[3];
            },
            $content
        );

        return $content;
    }

    /**
     * Import a single WS Form using WS Form's own API sequence.
     */
    private static function import_wsform( $wsf_entry ) {
        global $wpdb;

        if ( ! class_exists( 'WS_Form_Form' ) ) {
            return new WP_Error( 'no_wsf', 'WS_Form_Form class not found. Is WS Form active?' );
        }

        $label       = $wsf_entry['label']      ?? '';
        $form_object = $wsf_entry['form_object'] ?? null;

        if ( ! $form_object ) {
            return new WP_Error( 'no_form_data', 'No form_object in export entry.' );
        }

        if ( is_array( $form_object ) ) {
            $form_object = json_decode( wp_json_encode( $form_object ) );
        }

        $table       = $wpdb->prefix . 'wsf_form';
        $existing_id = $label
            ? $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE label = %s AND NOT (status = 'trash') LIMIT 1", $label ) )
            : null;

        $is_new = false;

        try {
            $ws_form_form = new WS_Form_Form();

            if ( $existing_id ) {
                $ws_form_form->id = (int) $existing_id;
                $form_object->id  = (int) $existing_id;
            } else {
                $ws_form_form->db_create();
                $form_object->id = $ws_form_form->id;
                $is_new          = true;
            }

            $ws_form_form->db_import_reset();
            $form_object->status = 'publish';
            $ws_form_form->db_update_from_object( $form_object, true, true );
            $ws_form_form->db_conditional_repair();
            $ws_form_form->db_action_repair();
            $ws_form_form->db_meta_repair();
            $ws_form_form->db_checksum();
            $ws_form_form->db_style_resolve();

        } catch ( Exception $e ) {
            return new WP_Error( 'wsf_import_failed', $e->getMessage() );
        }

        return [ 'id' => $ws_form_form->id, 'is_new' => $is_new ];
    }

    private static function merge_loops( $incoming ) {
        if ( empty( $incoming ) || ! is_array( $incoming ) ) {
            return [ 'merged' => 0, 'skipped' => 0 ];
        }
        $dest = get_option( 'etch_loops', [] );
        if ( is_string( $dest ) ) $dest = maybe_unserialize( $dest );
        if ( ! is_array( $dest ) ) $dest = [];
        $merged = $skipped = 0;
        foreach ( $incoming as $id => $loop ) {
            $is_new = ! isset( $dest[ $id ] );
            $dest[ $id ] = $loop;
            $is_new ? $merged++ : $skipped++;
        }
        update_option( 'etch_loops', $dest );
        return [ 'merged' => $merged, 'skipped' => $skipped ];
    }

    private static function merge_global_stylesheets( $incoming ) {
        if ( empty( $incoming ) || ! is_array( $incoming ) ) {
            return [ 'merged' => 0, 'skipped' => 0 ];
        }
        $dest = get_option( 'etch_global_stylesheets', [] );
        if ( is_string( $dest ) ) $dest = maybe_unserialize( $dest );
        if ( ! is_array( $dest ) ) $dest = [];
        $merged = $skipped = 0;
        foreach ( $incoming as $id => $sheet ) {
            $is_new = ! isset( $dest[ $id ] );
            $dest[ $id ] = $sheet;
            $is_new ? $merged++ : $skipped++;
        }
        update_option( 'etch_global_stylesheets', $dest );
        return [ 'merged' => $merged, 'skipped' => $skipped ];
    }

    private static function merge_styles( $incoming ) {
        if ( empty( $incoming ) || ! is_array( $incoming ) ) {
            return [ 'merged' => 0, 'skipped' => 0 ];
        }
        $dest = get_option( 'etch_styles', [] );
        if ( is_string( $dest ) ) $dest = maybe_unserialize( $dest );
        if ( ! is_array( $dest ) ) $dest = [];
        $merged = $skipped = 0;
        foreach ( $incoming as $id => $style ) {
            if ( isset( $dest[ $id ] ) ) { $skipped++; }
            else { $dest[ $id ] = $style; $merged++; }
        }
        update_option( 'etch_styles', $dest );
        return [ 'merged' => $merged, 'skipped' => $skipped ];
    }
}
