<?php
if ( ! defined( 'ABSPATH' ) ) exit;

class Etch_Transfer_Importer {

    public static function import( $json, $options = [] ) {
        if ( function_exists( 'set_time_limit' ) ) @set_time_limit( 120 );
        @ini_set( 'memory_limit', '256M' );

        if ( empty( $json ) ) return new WP_Error( 'no_data', 'No JSON data provided.' );

        $data = json_decode( $json, true );
        if ( json_last_error() !== JSON_ERROR_NONE ) return new WP_Error( 'json_parse_error', 'Could not parse JSON: ' . json_last_error_msg() );

        if ( isset( $data['success'] ) && isset( $data['data'] ) ) $data = $data['data'];

        if ( ! $data || ! isset( $data['etch_export_version'] ) ) {
            return new WP_Error( 'invalid_json', 'Invalid export file. Please use a file generated by Etch Transfer.' );
        }

        // Normalise single-item export into multi shape
        if ( ! isset( $data['etch_export_type'] ) || $data['etch_export_type'] !== 'multi' ) {
            $data = [
                'etch_export_version'     => $data['etch_export_version'],
                'etch_export_type'        => 'multi',
                'source_site'             => $data['source_site'] ?? '',
                'source_theme'            => $data['source_theme'] ?? '',
                'item_count'              => 1,
                'items'                   => [ $data ],
                'wsf_forms'               => [],
                'etch_styles'             => $data['etch_styles'] ?? [],
                'etch_global_stylesheets' => [],
                'etch_loops'              => [],
                'media'                   => [],
                'style_fingerprints'      => [],
                'taxonomies'              => [],
            ];
        }

        if ( ! empty( $options['dry_run'] ) ) return self::analyse_bundle( $data );

        return self::process_bundle( $data, $options );
    }

    // ── DRY RUN ───────────────────────────────────────────────────────────────

    private static function analyse_bundle( $data ) {
        global $wpdb;

        $report = [
            'dry_run'         => true,
            'source_site'     => $data['source_site'] ?? '',
            'items'           => [],
            'style_conflicts' => [],
            'wsf_conflicts'   => [],
            'media_count'     => count( $data['media'] ?? [] ),
        ];

        // Posts / templates / components
        foreach ( ( $data['items'] ?? [] ) as $item ) {
            $existing        = self::find_existing( $item );
            $report['items'][] = [
                'title'        => $item['post_title'] ?? '?',
                'type'         => $item['source_post_type'] ?? '?',
                'is_component' => ! empty( $item['is_component'] ),
                'action'       => $existing ? 'update' : 'create',
                'dest_id'      => $existing ? $existing->ID : null,
            ];
        }

        // WS Forms
        if ( ! empty( $data['wsf_forms'] ) ) {
            $table        = $wpdb->prefix . 'wsf_form';
            $table_exists = $wpdb->get_var( "SHOW TABLES LIKE '{$table}'" ) === $table;
            foreach ( $data['wsf_forms'] as $entry ) {
                $label   = $entry['label'] ?? '(untitled form)';
                $action  = 'create';
                $dest_id = null;
                if ( $table_exists && $label ) {
                    $existing_id = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE label = %s AND status != 'trash' LIMIT 1", $label ) );
                    if ( $existing_id ) {
                        $action   = 'update';
                        $dest_id  = intval( $existing_id );
                        $report['wsf_conflicts'][] = [ 'label' => $label, 'dest_id' => $dest_id ];
                    }
                }
                $report['items'][] = [ 'title' => $label, 'type' => 'wsf_form', 'action' => $action, 'dest_id' => $dest_id ];
            }
        }

        // Global Stylesheets
        $dest_gss = get_option( 'etch_global_stylesheets', [] );
        if ( is_string( $dest_gss ) ) $dest_gss = maybe_unserialize( $dest_gss );
        foreach ( ( $data['etch_global_stylesheets'] ?? [] ) as $id => $sheet ) {
            $report['items'][] = [
                'title'   => $sheet['name'] ?? $id,
                'type'    => 'global_stylesheet',
                'action'  => isset( $dest_gss[ $id ] ) ? 'update' : 'create',
                'dest_id' => null,
            ];
        }

        // Loops
        $dest_loops = get_option( 'etch_loops', [] );
        if ( is_string( $dest_loops ) ) $dest_loops = maybe_unserialize( $dest_loops );
        foreach ( ( $data['etch_loops'] ?? [] ) as $id => $loop ) {
            $report['items'][] = [
                'title'   => $loop['name'] ?? $id,
                'type'    => 'loop',
                'action'  => isset( $dest_loops[ $id ] ) ? 'update' : 'create',
                'dest_id' => null,
            ];
        }

        // Standalone taxonomies
        foreach ( ( $data['taxonomies'] ?? [] ) as $tax_slug => $tax_data ) {
            $label       = $tax_data['label'] ?? $tax_slug;
            $term_count  = count( $tax_data['terms'] ?? [] );
            $report['items'][] = [
                'title'   => $label . " ({$term_count} terms)",
                'type'    => 'taxonomy',
                'action'  => 'merge',
                'dest_id' => null,
            ];
        }

        // Style conflicts
        $dest_styles     = get_option( 'etch_styles', [] );
        if ( is_string( $dest_styles ) ) $dest_styles = maybe_unserialize( $dest_styles );
        $incoming_fps    = $data['style_fingerprints'] ?? [];
        $incoming_styles = $data['etch_styles'] ?? [];
        foreach ( $incoming_styles as $id => $style ) {
            if ( isset( $dest_styles[ $id ] ) ) {
                $dest_fp     = md5( $dest_styles[ $id ]['css'] ?? '' );
                $incoming_fp = $incoming_fps[ $id ] ?? md5( $style['css'] ?? '' );
                if ( $dest_fp !== $incoming_fp ) {
                    $report['style_conflicts'][] = [ 'id' => $id, 'selector' => $style['selector'] ?? $id ];
                }
            }
        }

        return $report;
    }

    // ── ACTUAL IMPORT ─────────────────────────────────────────────────────────

    private static function process_bundle( $data, $options = [] ) {
        global $wpdb;

        $style_conflict_mode = $options['style_conflicts'] ?? 'skip';
        $import_media        = ! empty( $options['import_media'] );

        $imported     = [];
        $created      = [];
        $errors       = [];
        $item_log     = [];
        $wsf_imported = [];
        $wsf_created  = [];
        $wsf_id_map   = [];
        $created_post_ids = [];

        // Sideload media first
        $media_id_map = [];
        if ( $import_media && ! empty( $data['media'] ) ) {
            foreach ( $data['media'] as $old_id => $media_entry ) {
                $new_id = self::sideload_media( $media_entry );
                if ( $new_id && ! is_wp_error( $new_id ) ) $media_id_map[ intval( $old_id ) ] = $new_id;
            }
        }

        // Import standalone taxonomies first (so terms exist for post assignment)
        foreach ( ( $data['taxonomies'] ?? [] ) as $tax_slug => $tax_data ) {
            self::import_taxonomy_terms( $tax_slug, $tax_data['terms'] ?? [] );
        }

        // WS Forms
        foreach ( ( $data['wsf_forms'] ?? [] ) as $wsf_entry ) {
            $result = self::import_wsform( $wsf_entry );
            if ( is_wp_error( $result ) ) { $errors[] = '"' . ( $wsf_entry['label'] ?? '?' ) . '": ' . $result->get_error_message(); continue; }
            $old_id = intval( $wsf_entry['source_form_id'] ?? ( is_array( $wsf_entry['form_object'] ) ? ( $wsf_entry['form_object']['id'] ?? 0 ) : 0 ) );
            if ( $old_id > 0 ) $wsf_id_map[ $old_id ] = $result['id'];
            $result['is_new'] ? ( $wsf_created[] = $wsf_entry['label'] ?? '(untitled)' ) : ( $wsf_imported[] = $wsf_entry['label'] ?? '(untitled)' );
        }

        // Build destination component map
        $dest_component_map = [];
        $dest_blocks = $wpdb->get_results( "SELECT ID, post_title FROM {$wpdb->posts} WHERE post_type = 'wp_block' AND post_status != 'trash'", ARRAY_A );
        if ( $dest_blocks ) foreach ( $dest_blocks as $row ) $dest_component_map[ $row['post_title'] ] = intval( $row['ID'] );

        // Components before pages
        usort( $data['items'], function( $a, $b ) {
            $a_block = ( $a['source_post_type'] ?? '' ) === 'wp_block';
            $b_block = ( $b['source_post_type'] ?? '' ) === 'wp_block';
            return (int) $b_block - (int) $a_block;
        });

        foreach ( ( $data['items'] ?? [] ) as $item ) {
            $dest_post = self::resolve_destination( $item );
            if ( is_wp_error( $dest_post ) ) {
                $errors[]   = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $dest_post->get_error_message();
                $item_log[] = [ 'title' => $item['post_title'] ?? '?', 'status' => 'error', 'message' => $dest_post->get_error_message() ];
                continue;
            }

            $is_new = isset( $dest_post->_is_new ) && $dest_post->_is_new;
            if ( $is_new ) {
                $created_post_ids[] = $dest_post->ID;
                $dest_component_map[ $item['post_title'] ] = $dest_post->ID;
            }

            $post_content          = $item['post_content']          ?? '';
            $post_content_filtered = $item['post_content_filtered'] ?? '';

            $component_name_map = $item['component_name_map'] ?? [];
            if ( ! empty( $component_name_map ) && ! empty( $dest_component_map ) ) {
                $post_content          = self::rewrite_component_refs_by_name( $post_content,          $component_name_map, $dest_component_map );
                $post_content_filtered = self::rewrite_component_refs_by_name( $post_content_filtered, $component_name_map, $dest_component_map );
            }
            if ( ! empty( $wsf_id_map ) )   $post_content = self::rewrite_wsf_ids( $post_content, $wsf_id_map );
            if ( ! empty( $media_id_map ) ) {
                $post_content          = self::rewrite_media_ids( $post_content,          $media_id_map );
                $post_content_filtered = self::rewrite_media_ids( $post_content_filtered, $media_id_map );
            }

            $item['post_content']          = $post_content;
            $item['post_content_filtered'] = $post_content_filtered;

            $result = self::write_post( $item, $dest_post->ID );
            if ( is_wp_error( $result ) ) {
                $errors[]   = '"' . ( $item['post_title'] ?? '?' ) . '": ' . $result->get_error_message();
                $item_log[] = [ 'title' => $item['post_title'] ?? '?', 'status' => 'error', 'message' => $result->get_error_message() ];
                if ( $is_new ) { wp_delete_post( $dest_post->ID, true ); $created_post_ids = array_diff( $created_post_ids, [ $dest_post->ID ] ); }
                continue;
            }

            // Re-assign taxonomy terms
            if ( ! empty( $item['post_taxonomies'] ) ) {
                self::assign_post_taxonomies( $dest_post->ID, $item['post_taxonomies'] );
            }

            if ( $is_new ) { $created[] = $item['post_title'] ?? '(untitled)'; $item_log[] = [ 'title' => $item['post_title'] ?? '?', 'status' => 'created', 'dest_id' => $dest_post->ID ]; }
            else           { $imported[] = $item['post_title'] ?? '(untitled)'; $item_log[] = [ 'title' => $item['post_title'] ?? '?', 'status' => 'updated', 'dest_id' => $dest_post->ID ]; }
        }

        $styles      = self::merge_styles( $data['etch_styles'] ?? [], $style_conflict_mode, $data['style_fingerprints'] ?? [] );
        $gss_result  = self::merge_global_stylesheets( $data['etch_global_stylesheets'] ?? [] );
        $loop_result = self::merge_loops( $data['etch_loops'] ?? [] );

        wp_cache_flush();

        $parts = [];
        if ( ! empty( $imported )     ) $parts[] = count( $imported )     . ' updated';
        if ( ! empty( $created )      ) $parts[] = count( $created )      . ' created';
        if ( ! empty( $wsf_imported ) ) $parts[] = count( $wsf_imported ) . ' WS Forms updated';
        if ( ! empty( $wsf_created )  ) $parts[] = count( $wsf_created )  . ' WS Forms created';
        if ( ! empty( $media_id_map ) ) $parts[] = count( $media_id_map ) . ' media files imported';
        if ( ! empty( $errors )       ) $parts[] = count( $errors )       . ' failed';

        $msg = 'Import complete from ' . ( $data['source_site'] ?? 'unknown' ) . '. '
             . ( $parts ? implode( ', ', $parts ) . '. ' : '' )
             . $styles['merged'] . ' Etch styles merged'
             . ( $styles['conflicts'] > 0 ? ' (' . $styles['conflicts'] . ' conflicts ' . $style_conflict_mode . 'd)' : '' ) . '. '
             . $gss_result['merged'] . ' global stylesheets merged. '
             . $loop_result['merged'] . ' loops merged.';

        if ( ! empty( $errors ) ) $msg .= ' Errors: ' . implode( '; ', $errors );

        return [ 'message' => $msg, 'imported' => array_merge( $imported, $wsf_imported ), 'created' => array_merge( $created, $wsf_created ), 'errors' => $errors, 'styles_merged' => $styles['merged'], 'item_log' => $item_log ];
    }

    // ── TAXONOMY IMPORT ───────────────────────────────────────────────────────

    /**
     * Import / merge terms into a taxonomy.
     * Creates parent terms before children. Skips terms that already exist by slug.
     */
    private static function import_taxonomy_terms( $tax_slug, $terms ) {
        if ( ! taxonomy_exists( $tax_slug ) || empty( $terms ) ) return;

        // Two passes: parents first, then children
        foreach ( [ true, false ] as $parents_only ) {
            foreach ( $terms as $term ) {
                $has_parent = ! empty( $term['parent_slug'] );
                if ( $parents_only && $has_parent ) continue;
                if ( ! $parents_only && ! $has_parent ) continue;

                $existing = get_term_by( 'slug', $term['slug'], $tax_slug );
                if ( $existing ) continue; // already exists — don't overwrite

                $args = [ 'slug' => $term['slug'], 'description' => $term['description'] ?? '' ];
                if ( $has_parent ) {
                    $parent = get_term_by( 'slug', $term['parent_slug'], $tax_slug );
                    if ( $parent ) $args['parent'] = $parent->term_id;
                }
                wp_insert_term( $term['name'], $tax_slug, $args );
            }
        }
    }

    /**
     * Assign taxonomy terms back to a post after import.
     * If a term doesn't exist on the destination site it is created (with its
     * parent, if one is recorded) so that the assignment never silently fails.
     */
    private static function assign_post_taxonomies( $post_id, $post_taxonomies ) {
        foreach ( $post_taxonomies as $tax_slug => $terms ) {
            if ( ! taxonomy_exists( $tax_slug ) ) continue;

            // Two passes: parents before children, mirroring import_taxonomy_terms().
            foreach ( [ true, false ] as $parents_only ) {
                foreach ( $terms as $term_data ) {
                    $has_parent = ! empty( $term_data['parent_slug'] );
                    if ( $parents_only && $has_parent ) continue;
                    if ( ! $parents_only && ! $has_parent ) continue;

                    if ( ! get_term_by( 'slug', $term_data['slug'], $tax_slug ) ) {
                        $args = [
                            'slug'        => $term_data['slug'],
                            'description' => $term_data['description'] ?? '',
                        ];
                        if ( $has_parent ) {
                            $parent = get_term_by( 'slug', $term_data['parent_slug'], $tax_slug );
                            if ( $parent ) $args['parent'] = $parent->term_id;
                        }
                        wp_insert_term( $term_data['name'], $tax_slug, $args );
                    }
                }
            }

            $term_ids = [];
            foreach ( $terms as $term_data ) {
                $term = get_term_by( 'slug', $term_data['slug'], $tax_slug );
                if ( $term ) $term_ids[] = $term->term_id;
            }
            if ( ! empty( $term_ids ) ) wp_set_object_terms( $post_id, $term_ids, $tax_slug );
        }
    }

    // ── MEDIA SIDELOAD ────────────────────────────────────────────────────────

    private static function sideload_media( $entry ) {
        if ( empty( $entry['data'] ) || empty( $entry['filename'] ) ) return null;

        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';

        $tmp = wp_tempnam( $entry['filename'] );
        if ( ! $tmp ) return null;

        file_put_contents( $tmp, base64_decode( $entry['data'] ) );
        $file_array = [ 'name' => $entry['filename'], 'tmp_name' => $tmp, 'error' => 0, 'size' => filesize( $tmp ) ];
        $att_id = media_handle_sideload( $file_array, 0, $entry['title'] ?? '' );
        @unlink( $tmp );
        if ( is_wp_error( $att_id ) ) return null;
        if ( ! empty( $entry['alt'] ) ) update_post_meta( $att_id, '_wp_attachment_image_alt', $entry['alt'] );
        return $att_id;
    }

    // ── REWRITERS ─────────────────────────────────────────────────────────────

    private static function rewrite_media_ids( $content, $id_map ) {
        if ( empty( $content ) || empty( $id_map ) ) return $content;

        // etch/dynamic-image — "mediaId":"OLD" or "mediaId":OLD
        $content = preg_replace_callback( '/"mediaId"\s*:\s*"?(\d+)"?/', function( $m ) use ( $id_map ) {
            $new    = $id_map[ intval( $m[1] ) ] ?? intval( $m[1] );
            $quoted = strpos( $m[0], '"mediaId":"' ) !== false;
            return $quoted ? '"mediaId":"' . $new . '"' : '"mediaId":' . $new;
        }, $content );

        // etch/element imageData — "attachmentId":OLD
        $content = preg_replace_callback( '/"attachmentId"\s*:\s*(\d+)/', function( $m ) use ( $id_map ) {
            return '"attachmentId":' . ( $id_map[ intval( $m[1] ) ] ?? intval( $m[1] ) );
        }, $content );

        // wp:image block JSON
        $content = preg_replace_callback( '/(wp:image\s+\{[^}]*"id"\s*:\s*)(\d+)/i', function( $m ) use ( $id_map ) {
            return $m[1] . ( $id_map[ intval( $m[2] ) ] ?? intval( $m[2] ) );
        }, $content );

        // wp:gallery ids array
        $content = preg_replace_callback( '/"ids"\s*:\s*\[([^\]]+)\]/', function( $m ) use ( $id_map ) {
            $new_ids = array_map( function( $id ) use ( $id_map ) {
                $int = intval( trim( $id ) ); return $id_map[ $int ] ?? $int;
            }, explode( ',', $m[1] ) );
            return '"ids":[' . implode( ',', $new_ids ) . ']';
        }, $content );

        // HTML class wp-image-NNN
        $content = preg_replace_callback( '/wp-image-(\d+)/', function( $m ) use ( $id_map ) {
            return 'wp-image-' . ( $id_map[ intval( $m[1] ) ] ?? intval( $m[1] ) );
        }, $content );

        // etch/component prop values — rewrite numeric wpMediaId prop values
        // inside the "attributes":{} object of wp:etch/component block comments.
        $content = preg_replace_callback(
            '/(<!--\s*wp:etch\/component\s+)(\{[^}]*(?:\{[^}]*\}[^}]*)*\})(\s*(?:\/)?-->)/i',
            function ( $m ) use ( $id_map ) {
                $block_data = json_decode( $m[2], true );
                if ( ! is_array( $block_data ) || empty( $block_data['attributes'] ) ) return $m[0];

                $ref             = isset( $block_data['ref'] ) ? intval( $block_data['ref'] ) : 0;
                $media_prop_keys = ( $ref > 0 ) ? self::get_dest_component_media_prop_keys( $ref ) : [];

                $changed = false;
                foreach ( $block_data['attributes'] as $key => &$value ) {
                    $int_val = intval( $value );
                    if ( $int_val <= 0 ) continue;
                    // Rewrite if key is a known wpMediaId prop, or fallback to any
                    // pure-integer value when prop definitions aren't available.
                    $is_media_prop = ! empty( $media_prop_keys )
                        ? in_array( $key, $media_prop_keys, true )
                        : ( (string) $int_val === (string) $value );
                    if ( $is_media_prop && isset( $id_map[ $int_val ] ) ) {
                        $value   = is_string( $value ) ? (string) $id_map[ $int_val ] : $id_map[ $int_val ];
                        $changed = true;
                    }
                }
                unset( $value );

                if ( ! $changed ) return $m[0];
                $new_json = wp_json_encode( $block_data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
                return $m[1] . $new_json . $m[3];
            },
            $content
        );

        return $content;
    }

    /**
     * Like get_component_media_prop_keys in the exporter, but reads from the
     * destination site's component post (called during import, refs already remapped).
     */
    private static function get_dest_component_media_prop_keys( $ref_id ) {
        $keys      = [];
        $comp_post = get_post( $ref_id );
        if ( ! $comp_post ) return $keys;
        preg_match_all( '/<!--\s*wp:etch\/element\s+(\{.+?\})\s*(?:\/)?-->/is', $comp_post->post_content, $m );
        foreach ( $m[1] as $json_str ) {
            $attrs = json_decode( $json_str, true );
            if ( ! is_array( $attrs ) || empty( $attrs['properties'] ) ) continue;
            foreach ( $attrs['properties'] as $prop ) {
                if ( ( $prop['type']['specialized'] ?? '' ) === 'wpMediaId' ) $keys[] = $prop['key'];
            }
            if ( ! empty( $keys ) ) break;
        }
        return $keys;
    }

    private static function rewrite_component_refs_by_name( $content, $component_name_map, $dest_component_map ) {
        if ( empty( $content ) || empty( $component_name_map ) ) return $content;
        return preg_replace_callback(
            '/(<!--\s*wp:etch\/component\s+\{[^}]*"ref"\s*:\s*)(\d+)/i',
            function ( $matches ) use ( $component_name_map, $dest_component_map ) {
                $src_id = $matches[2];
                $name   = $component_name_map[ $src_id ] ?? ( $component_name_map[ (int) $src_id ] ?? null );
                if ( $name !== null && isset( $dest_component_map[ $name ] ) ) return $matches[1] . $dest_component_map[ $name ];
                return $matches[0];
            },
            $content
        );
    }

    private static function rewrite_wsf_ids( $content, $id_map ) {
        if ( empty( $content ) || empty( $id_map ) ) return $content;
        $content = preg_replace_callback(
            '/(<!--\s*wp:wsf-block\/form-add\s+)(\{[^}]*"form_id"\s*:\s*")(\d+)(")/i',
            function ( $matches ) use ( $id_map ) { return $matches[1] . $matches[2] . ( $id_map[ intval( $matches[3] ) ] ?? $matches[3] ) . $matches[4]; },
            $content
        );
        $content = preg_replace_callback(
            '/(\[ws_form\b[^\]]*\bid\s*=\s*["\'])(\d+)(["\'][^\]]*\])/i',
            function ( $matches ) use ( $id_map ) { return $matches[1] . ( $id_map[ intval( $matches[2] ) ] ?? $matches[2] ) . $matches[3]; },
            $content
        );
        return $content;
    }

    // ── POST RESOLUTION ───────────────────────────────────────────────────────

    private static function find_existing( $item ) {
        global $wpdb;
        $post_type = $item['source_post_type'] ?? 'page';
        $slug      = $item['source_post_name']  ?? '';
        if ( $post_type === 'wp_template' ) {
            $bare_slug = str_contains( $slug, '//' ) ? substr( $slug, strpos( $slug, '//' ) + 2 ) : $slug;
            $id = $wpdb->get_var( $wpdb->prepare( "SELECT ID FROM {$wpdb->posts} WHERE post_type = 'wp_template' AND post_status != 'trash' AND ( post_name = %s OR post_name LIKE %s ) LIMIT 1", $bare_slug, '%//' . $wpdb->esc_like( $bare_slug ) ) );
            return $id ? get_post( $id ) : null;
        }
        if ( $slug ) {
            $existing = get_posts( [ 'post_type' => $post_type, 'name' => $slug, 'post_status' => 'any', 'posts_per_page' => 1 ] );
            return ! empty( $existing ) ? $existing[0] : null;
        }
        return null;
    }

    private static function resolve_destination( $item ) {
        global $wpdb;
        $post_type = $item['source_post_type'] ?? 'page';
        $slug      = $item['source_post_name']  ?? '';
        $title     = $item['post_title']         ?? '';

        if ( $post_type === 'wp_template' ) {
            $bare_slug  = str_contains( $slug, '//' ) ? substr( $slug, strpos( $slug, '//' ) + 2 ) : $slug;
            $dest_theme = get_stylesheet();
            $all_ids    = array_map( 'intval', (array) $wpdb->get_col( $wpdb->prepare( "SELECT ID FROM {$wpdb->posts} WHERE post_type = 'wp_template' AND post_status != 'trash' AND ( post_name = %s OR post_name LIKE %s ) ORDER BY ID ASC", $bare_slug, '%//' . $wpdb->esc_like( $bare_slug ) ) ) );
            if ( ! empty( $all_ids ) ) {
                $dest_id = $all_ids[0];
                foreach ( $all_ids as $candidate ) {
                    $terms = wp_get_object_terms( $candidate, 'wp_theme', [ 'fields' => 'names' ] );
                    if ( ! is_wp_error( $terms ) && in_array( $dest_theme, $terms, true ) ) { $dest_id = $candidate; break; }
                }
                wp_set_object_terms( $dest_id, $dest_theme, 'wp_theme', false );
                return get_post( $dest_id );
            }
            $new_id = wp_insert_post( [ 'post_title' => $title, 'post_name' => $bare_slug, 'post_type' => 'wp_template', 'post_status' => 'publish', 'post_content' => '' ], true );
            if ( is_wp_error( $new_id ) ) return new WP_Error( 'create_failed', 'Could not create template: ' . $new_id->get_error_message() );
            wp_set_object_terms( $new_id, $dest_theme, 'wp_theme', false );
            $post = get_post( $new_id ); $post->_is_new = true; return $post;
        }

        if ( $slug ) {
            $existing = get_posts( [ 'post_type' => $post_type, 'name' => $slug, 'post_status' => 'any', 'posts_per_page' => 1 ] );
            if ( ! empty( $existing ) ) return $existing[0];
        }
        $new_id = wp_insert_post( [ 'post_title' => $title, 'post_name' => $slug, 'post_type' => $post_type, 'post_status' => $item['post_status'] ?? 'publish', 'post_content' => '' ], true );
        if ( is_wp_error( $new_id ) ) return new WP_Error( 'create_failed', 'Could not create: ' . $new_id->get_error_message() );
        $post = get_post( $new_id ); $post->_is_new = true; return $post;
    }

    private static function write_post( $item, $dest_post_id ) {
        global $wpdb;
        $post_type = $item['source_post_type'] ?? 'post';
        $fields = [
            'post_title'            => $item['post_title']            ?? '',
            'post_status'           => 'publish',
            'post_content'          => $item['post_content']          ?? '',
            'post_content_filtered' => $item['post_content_filtered'] ?? '',
            'post_excerpt'          => $item['post_excerpt']          ?? '',
        ];
        if ( $post_type !== 'wp_template' ) $fields['post_name'] = $item['source_post_name'] ?? '';
        $updated = $wpdb->update( $wpdb->posts, $fields, [ 'ID' => $dest_post_id ] );
        if ( $updated === false ) return new WP_Error( 'db_error', 'DB write failed: ' . $wpdb->last_error );
        $wpdb->delete( $wpdb->postmeta, [ 'post_id' => $dest_post_id ], [ '%d' ] );
        foreach ( ( $item['meta'] ?? [] ) as $row ) {
            $wpdb->insert( $wpdb->postmeta, [ 'post_id' => $dest_post_id, 'meta_key' => $row['meta_key'], 'meta_value' => $row['meta_value'] ], [ '%d', '%s', '%s' ] );
        }
        clean_post_cache( $dest_post_id );
        return true;
    }

    // ── WSFORM IMPORT ─────────────────────────────────────────────────────────

    private static function import_wsform( $wsf_entry ) {
        global $wpdb;
        if ( ! class_exists( 'WS_Form_Form' ) ) return new WP_Error( 'no_wsf', 'WS_Form_Form class not found. Is WS Form active?' );
        $label       = $wsf_entry['label']      ?? '';
        $form_object = $wsf_entry['form_object'] ?? null;
        if ( ! $form_object ) return new WP_Error( 'no_form_data', 'No form_object in export entry.' );
        if ( is_array( $form_object ) ) $form_object = json_decode( wp_json_encode( $form_object ) );
        $table       = $wpdb->prefix . 'wsf_form';
        $existing_id = $label ? $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE label = %s AND NOT (status = 'trash') LIMIT 1", $label ) ) : null;
        $is_new      = false;
        try {
            $ws_form_form = new WS_Form_Form();
            if ( $existing_id ) { $ws_form_form->id = (int) $existing_id; $form_object->id = (int) $existing_id; }
            else { $ws_form_form->db_create(); $form_object->id = $ws_form_form->id; $is_new = true; }
            $ws_form_form->db_import_reset();
            $form_object->status = 'publish';
            $ws_form_form->db_update_from_object( $form_object, true, true );
            $ws_form_form->db_conditional_repair();
            $ws_form_form->db_action_repair();
            $ws_form_form->db_meta_repair();
            $ws_form_form->db_checksum();
            $ws_form_form->db_style_resolve();
        } catch ( Exception $e ) { return new WP_Error( 'wsf_import_failed', $e->getMessage() ); }
        return [ 'id' => $ws_form_form->id, 'is_new' => $is_new ];
    }

    // ── OPTION MERGERS ────────────────────────────────────────────────────────

    private static function merge_styles( $incoming, $mode = 'skip', $incoming_fps = [] ) {
        if ( empty( $incoming ) || ! is_array( $incoming ) ) return [ 'merged' => 0, 'skipped' => 0, 'conflicts' => 0 ];
        $dest = get_option( 'etch_styles', [] );
        if ( is_string( $dest ) ) $dest = maybe_unserialize( $dest );
        if ( ! is_array( $dest ) ) $dest = [];
        $merged = $skipped = $conflicts = 0;
        foreach ( $incoming as $id => $style ) {
            if ( ! isset( $dest[ $id ] ) ) { $dest[ $id ] = $style; $merged++; continue; }
            $is_conflict = md5( $dest[ $id ]['css'] ?? '' ) !== ( $incoming_fps[ $id ] ?? md5( $style['css'] ?? '' ) );
            if ( ! $is_conflict ) { $skipped++; continue; }
            $conflicts++;
            if ( $mode === 'overwrite' ) { $dest[ $id ] = $style; $merged++; }
            elseif ( $mode === 'rename' ) { $dest[ $id . '_imported_' . substr( md5( uniqid() ), 0, 6 ) ] = $style; $merged++; }
            else $skipped++;
        }
        update_option( 'etch_styles', $dest );
        return [ 'merged' => $merged, 'skipped' => $skipped, 'conflicts' => $conflicts ];
    }

    private static function merge_global_stylesheets( $incoming ) {
        if ( empty( $incoming ) || ! is_array( $incoming ) ) return [ 'merged' => 0, 'skipped' => 0 ];
        $dest = get_option( 'etch_global_stylesheets', [] );
        if ( is_string( $dest ) ) $dest = maybe_unserialize( $dest );
        if ( ! is_array( $dest ) ) $dest = [];
        $merged = $skipped = 0;
        foreach ( $incoming as $id => $sheet ) { $is_new = ! isset( $dest[ $id ] ); $dest[ $id ] = $sheet; $is_new ? $merged++ : $skipped++; }
        update_option( 'etch_global_stylesheets', $dest );
        return [ 'merged' => $merged, 'skipped' => $skipped ];
    }

    private static function merge_loops( $incoming ) {
        if ( empty( $incoming ) || ! is_array( $incoming ) ) return [ 'merged' => 0, 'skipped' => 0 ];
        $dest = get_option( 'etch_loops', [] );
        if ( is_string( $dest ) ) $dest = maybe_unserialize( $dest );
        if ( ! is_array( $dest ) ) $dest = [];
        $merged = $skipped = 0;
        foreach ( $incoming as $id => $loop ) { $is_new = ! isset( $dest[ $id ] ); $dest[ $id ] = $loop; $is_new ? $merged++ : $skipped++; }
        update_option( 'etch_loops', $dest );
        return [ 'merged' => $merged, 'skipped' => $skipped ];
    }
}
